# Generated by Django 5.2.3 on 2025-07-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='name',
            field=models.CharField(default='가수 미지정', max_length=100),
        ),
    ]
