# Generated by Django 5.2.3 on 2025-07-13 12:01

import singer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0003_singer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='singer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=singer.models.image_upload_path),
        ),
        migrations.AddField(
            model_name='singer',
            name='tags',
            field=models.ManyToManyField(blank=True, to='singer.tag'),
        ),
    ]
