# Generated by Django 5.2.3 on 2025-07-15 08:32

import django.db.models.deletion
import singer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0005_alter_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=singer.models.image_upload_path)),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='singer.singer')),
            ],
        ),
    ]
