# Generated by Django 5.2.3 on 2025-07-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0006_singerimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singer',
            name='image',
        ),
    ]
